using System.Text.Json.Serialization;

namespace ProgressSyntha.Models.Streaming;

// This class configures JSON serialization to use source generation for streaming models
// Source generation creates serialization code at compile time, eliminating reflection
// and improving performance across the application
[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
[JsonSerializable(typeof(RAGContent))]
[JsonSerializable(typeof(AnswerContent))]
[JsonSerializable(typeof(StatusContent))]
[JsonSerializable(typeof(MetaDataContent))]
[JsonSerializable(typeof(CitationsContent))]
[JsonSerializable(typeof(CitationItem))]
[JsonSerializable(typeof(RetrievalContent))]
[JsonSerializable(typeof(Results))]
[JsonSerializable(typeof(Relations))]
[JsonSerializable(typeof(BestMatch))]
[JsonSerializable(typeof(Resource))]
[JsonSerializable(typeof(Origin))]
[JsonSerializable(typeof(Metadata))]
[JsonSerializable(typeof(UserMetadata))]
[JsonSerializable(typeof(Classification))]
[JsonSerializable(typeof(ComputedMetadata))]
[JsonSerializable(typeof(FieldClassification))]
[JsonSerializable(typeof(Field))]
[JsonSerializable(typeof(Data))]
[JsonSerializable(typeof(TextValueWrapper))]
[JsonSerializable(typeof(TextValue))]
[JsonSerializable(typeof(FileValueWrapper))]
[JsonSerializable(typeof(FileValue))]
[JsonSerializable(typeof(FileDetails))]
[JsonSerializable(typeof(LinkValueWrapper))]
[JsonSerializable(typeof(LinkValue))]
[JsonSerializable(typeof(GenericValueWrapper))]
[JsonSerializable(typeof(FieldContainer))]
[JsonSerializable(typeof(Paragraph))]
[JsonSerializable(typeof(ParagraphPosition))]
[JsonSerializable(typeof(AugmentedContext))]
[JsonSerializable(typeof(Tokens))]
[JsonSerializable(typeof(Timings))]
[JsonSerializable(typeof(DebugContent))]
[JsonSerializable(typeof(DebugMetadata))]
[JsonSerializable(typeof(PredictRequest))]
[JsonSerializable(typeof(DebugMetrics))]
[JsonSerializable(typeof(MainQueryMetrics))]
[JsonSerializable(typeof(HybridRetrievalMetrics))]
[JsonSerializable(typeof(AskMetrics))]
[JsonSerializable(typeof(MinScore))]
[JsonSerializable(typeof(Dictionary<string, int[][]>))]
[JsonSerializable(typeof(Dictionary<string, Resource>))]
[JsonSerializable(typeof(Dictionary<string, object>))]
[JsonSerializable(typeof(Dictionary<string, TextValueWrapper>))]
[JsonSerializable(typeof(Dictionary<string, FileValueWrapper>))]
[JsonSerializable(typeof(Dictionary<string, LinkValueWrapper>))]
[JsonSerializable(typeof(Dictionary<string, GenericValueWrapper>))]
[JsonSerializable(typeof(Dictionary<string, FieldContainer>))]
[JsonSerializable(typeof(Dictionary<string, Paragraph>))]
[JsonSerializable(typeof(Dictionary<string, double>))]
[JsonSerializable(typeof(List<BestMatch>))]
[JsonSerializable(typeof(List<string>))]
[JsonSerializable(typeof(List<object>))]
[JsonSerializable(typeof(List<Classification>))]
[JsonSerializable(typeof(List<FieldClassification>))]
internal partial class StreamingModelsContext : JsonSerializerContext
{
}